apiVersion: v1
kind: Service
metadata:
  name: snipe-entrypoint
  labels:
    app: snipe
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008

  selector:
    app: snipe
    tier: frontend
 

---
apiVersion: v1
kind: Service
metadata:
  name: snipedb
  labels:
    app: snipedb
spec:
  ports:
    - port: 3306
  selector:
    app: snipe
    tier: snipedb
  